version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    command: mongod --port 27016
    ports:
      -   27016:27017
    container_name: mongo-container
    network_mode: host

  eureka:
    image: eureka
    restart: always
    container_name: eureka-container
    ports:
      - 8062:8062
    network_mode: host
    build:
      EurekaServer/
    expose:
      - 8062


  Muzix:
    image: spring-image
    restart: always
    build:
      MongoDB/
    container_name: spring-boot-container
    network_mode: host
    depends_on:
      - mongodb
      - zuul
      - eureka
    ports:
      - 8085:8085
    expose:
      - 8085

  zuul:
    image: zuul-image
    restart: always
    container_name: zuul-container
    network_mode: host
    build:
      Zuul/
    ports:
      - 8061:8061
    expose:
      - 8061

  configServer:
    image: config-image
    restart: always
    container_name: config-container
    network_mode: host
    build:
      configserver/
    ports:
      - 8888:8888

